### ISSUE TITLE
Adjust tables formatting to account for TinyMCE quirks

### ISSUE THREAD

**Issue by cferdinandi** [mashery/sparrow#17]
Don't target only `th`, as GUI will use `tr` inside `thead`.

```scss
/**
 * @section Tables
 * Styling for tables
 */

table {
	border-collapse: collapse;
	border-spacing: 0;
	margin-bottom: $spacing;
	max-width: 100%;
	width: 100%;
}

th,
td {
	text-align: left;
	padding: calc-em(8px);
}

thead {
	border-bottom: calc-em(2px) solid $color-gray-light;
}

th,
thead td {
	// background-color: lighten( $color-gray-light, 5% );
	font-weight: bold;
	vertical-align: bottom;
}

tbody tr {
	border-top: calc-em(1px) solid $color-gray-light;
}

td {
	vertical-align: top;
}

/**
 * Adds zebra striping
 */
.table-striped tbody tr:nth-child(odd) {
	background-color: lighten( $color-gray-light, 7% );
}


/**
 * Reduces padding on condensed tables
 */
.table-condensed th,
.table-condensed td, {
	padding: calc-em(4px);
}


/**
 * Pure CSS responsive tables
 * Adds label to each cell using the [data-label] attribute
 * @link https://techblog.livingsocial.com/blog/2015/04/06/responsive-tables-in-pure-css/
 */
@media (max-width: $bp-medium) {
	.table-responsive {

		thead {
			display: none;
			visibility: hidden;
		}

		tr {
			border-top: calc-em(1px) solid lighten( $color-gray-light, 3% );
			display: block;
			padding: calc-em(8px);
		}

		td {
			border: 0;
			display: block;
			padding: calc-em(4px);

			&:before {
				content: attr(data-label);
				display: block;
				font-weight: bold;
			}
		}

	}
}
```

```js
/**
 * Add table headers that are missing from the GUI generate tables
 */
var addTableHeaders = function () {

	'use strict';

	// Feature test
	var supports = 'querySelector' in document;
	if ( !supports ) return;

	// Variables
	var tables = document.querySelectorAll( 'table' );


	/**
	 * Get the closest matching element up the DOM tree.
	 * @param  {Element} elem     Starting element
	 * @param  {String}  selector Selector to match against (class, ID, data attribute, or tag)
	 * @return {Boolean|Element}  Returns null if not match found
	 */
	var getTbody = function ( elem ) {
		for ( ; elem && elem !== document && elem.nodeType === 1; elem = elem.parentNode ) {
			if ( elem.tagName.toLowerCase() === 'tbody' ) {
				return elem;
			}
		}
		return null;
	};


	for (var i = 0; i < tables.length; i++) {

		// Check if a table head already exists
		var thead = tables[i].querySelector( 'thead' );
		if ( thead ) continue;

		// Get the first table row and conver it to a thead
		var row = tables[i].querySelector('tr');
		var tbody = getTbody( row );
		if ( !row || !tbody ) continue;
		thead = document.createElement('thead');
		thead.innerHTML = '<tr>' + row.innerHTML + '</tr>';
		console.log(tbody.parentNode);
		tbody.parentNode.insertBefore( thead, tbody );
		row.parentNode.removeChild( row );
	}

};
```

```js
// Run script initializations when the Portal is ready
portalReady(function () {
    astro.init();
    clickToHighlight.init();
    fluidvids.init({
        selector: ['iframe', 'object'], // runs querySelectorAll()
        players: ['www.youtube.com', 'player.vimeo.com'] // players to support
    });
    houdini.init();
    modals.init();
    rightHeight.init();
    smoothScroll.init();
    stickyFooter.init();
    tabby.init();
    addTableHeaders();
});
```

### WYSIWYG Generated Tables

The Mashery Portal WYSIWYG generates tables that are missing the required `<thead>` and `<th>` elements. You can fix this by calling the `addTableHeaders()` JavaScript method. This is done for you already in the *Body JavaScript* section of *Portal Setup* in the Dashboard.

```js
portalReady(function () {
	addTableHeaders();
});
```
