### ISSUE TITLE
Fix table layout on Search

### ISSUE THREAD

**Issue by cferdinandi** [mashery/sparrow#22]
```scss
thead {
	border-bottom: calc-em(2px) solid $color-gray-light;

	.search-form & {
		border-bottom: 0;
	}
}

th,
thead td {
	// background-color: lighten( $color-gray-light, 5% );
	font-weight: bold;
	vertical-align: bottom;

	.search-form & {
		vertical-align: top;
	}
}
```
