### ISSUE TITLE
Fix bold search terms on search page

### ISSUE THREAD

**Issue by cferdinandi** [mashery/sparrow#61]
```scss
th,
thead td {
	// background-color: lighten( $color-gray-light, 5% );
	font-weight: bold;
	vertical-align: bottom;

	.page-search & {
		font-weight: normal;
	}

	.search-form & {
		vertical-align: top;
	}
}
```
